### ISSUE TITLE
Create PastOrder class

### ISSUE THREAD

**Issue by quot** [Rainforest-Group/Rainforest#10]
The user will keep track of all of their past orders. This will be handled by making a PastOrder class that keeps track of each past order. When an order is processed, it will store all of its data in the database and create a new PastOrder object. This object is then stored in an array of other PastOrder objects within the User object they are all associated with.

When a new user object is created, all of the past orders associated with that user should be pulled in from the database, stored within PastOrder objects, which are then stored within the user object's past order array.

What needs to be done for this task:

- Create PastOrder class
- Override ProcessOrder() function to prevent an order from being processed twice. (This can just be an empty function but it needs to be overriden to prevent this).
- When a User object is created, have the User class pull in past orders from the database and create new PastOrder object based on the information it has pulled in.

**Comment by har96** [comment]
If we wanted to consolidate our classes, we could just add an attribute to the order class that indicates whether or not the order has been completed. Then we wouldn't need a separate class. Either way should work though.

**Comment by shillerman** [comment]
@har96 That is what I ended up doing.  So this is no longer an issue.
