### ISSUE TITLE
Remove Customer and Admin classes?

### ISSUE THREAD

**Issue by quot** [Rainforest-Group/Rainforest#13]
We have commented them out for now instead of removing them and are putting an "isAdmin" boolean variable in the User class. This boolean would be used instead of having whole new classes for each type.

If you know of a reason why we would need to keep these classes, let us know and we can move back to the classes that we commented out.

**Comment by quot** [comment]
@har96 @OmarOdaini

**Comment by har96** [comment]
Merging them to one class sounds good to me.

**Comment by shillerman** [comment]
This has been implemented
