### ISSUE TITLE
Test rainforestClasses.php

### ISSUE THREAD

**Issue by shillerman** [Rainforest-Group/Rainforest#18]
Test rainforestClasses.php as we fill it in.  If you fill in a class, comment which one here, and someone will test it.  When a class has been successfully tested, comment here.  If you test something and find a problem, also leave a comment, and I will get on it.  When testing, test all methods in the class, and check the database to make sure the the setters work and the getters are returning correct values.  Use testRainforestClasses.php

**Comment by shillerman** [comment]
Filled in Item class.

**Comment by shillerman** [comment]
Item class tested successfully.

**Comment by shillerman** [comment]
Inventory class filled in - needs testing

**Comment by shillerman** [comment]
Order class filled in - needs testing

**Comment by shillerman** [comment]
User class filled in - needs testing

**Comment by quot** [comment]
Inventory tests done. Minor bugs found and fixed in dd0cdb8c74431742e498775a31501867ef16c732.

**Comment by quot** [comment]
Order class tests done. Final tests finished in 47716f8df66aa2c976c8b9aad04d0290fc161486.

**Comment by quot** [comment]
User class is mostly done. I would say that it's safe to say that it is working properly as far as the PHP code goes. I am having issues with the User constructor, though. It isn't creating a new user in the database. I need to figure out if this is an issue with my test or the User class.

**Comment by quot** [comment]
All tests have been created and are passing after aeff1c27067e6f38509f74f66dbc02cec7d42d6f. Closing this issue for now.
